;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=saucer
type=0
frames=5
width=6
height=2
colour=0x00FF00FF
slowdown=6
[frame0]
00=" ____ "
01="/____\"
[frame1]
00=" ____ "
01="/___o\"
[frame2]
00=" ____ "
01="/__o_\"
[frame3]
00=" ____ "
01="/_o__\"
[frame4]
00=" ____ "
01="/o___\"
