;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=shiprev
type=0
frames=2
width=4
height=3
colour=0x0000FFFF
slowdown=3
[frame0]
00="   /"
01="-==~"
02="   \"
[frame1]
00="   /"
01="-=="
02="   \"
