;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=dragonfly
type=0
frames=2
width=11
height=7
colour=0x00FF00FF
slowdown=1
[frame0]
00="##       ##"
01="  ##(O)##"
02="   #\|/#"
03=" ##  |  ##"
04="##   |   ##"
05="     |"
06="     |"
[frame1]
00="#         #"
01=" ###(O)###"
02="  ##\|/##"
03=" ##  |  ##"
04=" #   |   #"
05="     |"
06="     |"