;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=w
type=0
frames=1
width=10
height=6
colour=0xFF0000FF
slowdown=30
[frame0]
00="__________"
01="|        |"
02="| \    / |"
03="|  \/\/  |"
04="|________| "
05="|********|"