;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=s_pressed
type=0
frames=1
width=10
height=6
colour=0xFFFF77FF
slowdown=30
[frame0]
00=""
01="__________"
02="|   ___  |"
03="|  |__   |"
04="|  ___|  |"
05="|________|"