;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=title
type=0
frames=8
width=76
height=8
colour=0x00FF00FF
slowdown=18
[frame0]
00="    ____                               ______         _____          "                 
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  _W_____"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="Controls: Use WASD to press the buttons. Press P to play and press Q to quit"
[frame1]
00="    ____                               ______         _____           "    
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  __A____"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="Controls: Use WASD to press the buttons. Press P to play and press Q to quit"
[frame2]
00="    ____                               ______         _____            " 
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  ___S___"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="Controls: Use WASD to press the buttons. Press P to play and press Q to quit"
[frame3]
00="    ____                               ______         _____             " 
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  ____D__"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="Controls: Use WASD to press the buttons. Press P to play and press Q to quit"
[frame4]
00="    ____                               ______         _____          "                 
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  _W_____"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="                         Powered by DragonShouryo"
[frame5]
00="    ____                               ______         _____           "    
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  __A____"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="                         Powered by DragonShouryo"
[frame6]
00="    ____                               ______         _____            " 
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  ___S___"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="                         Powered by DragonShouryo"
[frame7]
00="    ____                               ______         _____             " 
01="   / __ \_________ _____ _____  ____  / __/ /_  __   / ___/____ ___  ____D__"
02="  / / / / ___/ __ `/ __ `/ __ \/ __ \/ /_/ / / / /   \__ \/ __ `/ / / / ___/"
03=" / /_/ / /  / /_/ / /_/ / /_/ / / / / __/ / /_/ /   ___/ / /_/ / /_/ (__  )" 
04="/_____/_/   \__,_/\__, /\____/_/ /_/_/ /_/\__, /   /____/\__,_/\__, /____/"  
05="                 /____/                  /____/               /____/"
06=""
07="                         Powered by DragonShouryo"