;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=d
type=0
frames=1
width=10
height=6
colour=0x7777FFFF
slowdown=30
[frame0]
00=""
01="__________"
02="|  | \   |"
03="|  |  |  |"
04="|  | /   |"
05="|________|"