;DragonShouryo Sprite V1
[header]
version=1
[meta]
name=l
type=0
frames=1
width=10
height=10
colour=0xFFFFFFFF
slowdown=30
[frame0]
00=""
01=" ____"
02="|    \"
03="|     \"
04="|   _  \"
05="|  |_)  \"
06="|  | \  |"
07="|       |"
08="|       |"
09="|_______|"